### ISSUE TITLE
Make `fzy` respect the ido.nvim case sensitive option

### ISSUE THREAD

**Issue by alexanderjeurissen** [ido-nvim/core#16]
Currently `fzy` lua native hardcodes `is_case_sensitive` to false. This is also the default value for the case sensitivity option is ido.nvim.

I just created a PR on the `fzy-lua-native` package to make this configurable so that we can properly support configurable case sensitivity when using `fzy`

ref https://github.com/romgrk/fzy-lua-native/pull/11

**Comment by shoumodip** [comment]
I am including my own version of the `fzy.lua` file so that everything is done in one loop. The filtering and the suggestion calculation. This should drastically improve performance.

Case-sensitivity is not ignored in my `filter` function

**Comment by alexanderjeurissen** [comment]
I think it might not be worth it to duplicate the fzy.filter functionality

can't we just use the submodule, and then define our own `luaJIT` prefix generation function ?
That way we still have C level performance, but don't introduce additional code to maintain unnecessarily. I think the benefit of a single loop is negligible compared to two loops done in C.

**Comment by shoumodip** [comment]
In the default `fzy.positions` function, it generates the position and runs a for loop on every single position to convert it from 0-based indeces to 1-based indeces. It may seem trivial but stuff like that adds up over the number of items, and in fact it is *useless* considering we only need the last position.

Also the two loops I was talking about was this.
- Loop through every single item in the items list and filter them, loop through every single position in every single item
- Sort the results
- Loop through the results *again* to calculate the suggestion and filter out the fuzzy matches if `fuzzy_matching` is false

This is what I have got currently implemented in Ido
- Loop through the items, calculate suggestion and optional true-matches, and only grab the last position all in one go
- Sort

LuaJIT is **insanely** fast for a scripting language, with speeds almost comparable to C. However it is not as fast as C. Therefore every single optimization counts. I am not saying the double loop implementation is slow just because it is looping twice. I have actually tested both approaches and the latter feels quite a bit smoother, especially when I ran it through `fd -t f -H . $HOME`.

Of course this is what I feel. Let me know if the speed boost is not worth it. After all forcing it to filter 100000+ items (yes I have a lot of files, whatever) is not something most users would do. In that case I will remove my custom filter function and reduce the code-base complexity a bit, which is always a plus.

**Comment by alexanderjeurissen** [comment]
I think in hindsight that I agree with you, I tried playing around with the fzy implementation and the performance is definitely smoother.

For now I think we should be fine as is, let's revisit on a case by case basis if it poses a problem.
